version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      # シェルスクリプトのコマンド実行
      - run: |
              python3.7.1 -m venv venv
              source ./venv/bin/activate
              pip install pytest
              pytest
              # store_test_results:
              # path: test-results

