version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.1
    steps:
      - checkout
      # シェルスクリプトのコマンド実行
      - run: |
              python -m venv venv
              source ./venv/bin/activate
              pip install pytest
              pytest --junit-xml=test-results/pytest.xml
              # テスト結果を保存する
      - store_test_results:
          path: test-results

